<Project>

  <PropertyGroup>
    <_ParentDirectoryBuildPropsPath Condition="'$(_DirectoryBuildPropsFile)' != ''">$([System.IO.Path]::Combine('..', '$(_DirectoryBuildPropsFile)'))</_ParentDirectoryBuildPropsPath>
  </PropertyGroup>

  <Import Project="$(_ParentDirectoryBuildPropsPath)" Condition="Exists('$(_ParentDirectoryBuildPropsPath)')"/>

  <PropertyGroup>
    <WarningLevel>3</WarningLevel>
    <!-- <AnalysisLevel>preview</AnalysisLevel> -->
    <Features>strict</Features>
  </PropertyGroup>

  <PropertyGroup>
    <DefaultTargetFrameworks>net8.0;net10.0</DefaultTargetFrameworks>
    <!--<DefineConstants>PROFILE</DefineConstants>-->
    <!--<IsPackable>true</IsPackable>-->
  </PropertyGroup>

  <!--
  <PropertyGroup>
    <SourceLinkCreate>true</SourceLinkCreate>
    <SourceLinkOriginUrl>https://github.com/dotnet/orleans</SourceLinkOriginUrl>
  </PropertyGroup> -->

</Project>